server:
  port: 8082
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/User_Playlist_Db
  application:
    name: song-services
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_IP:localhost}:${EUREKA_SERVER_PORT:8761}/eureka
    fetchRegistry: true
    registerWithEureka: true